from bambulabs_api.states_info import GcodeState as GcodeState

class Printer:
    def __init__(
        self,
        access_code: str,
        serial: str,
        ip_address: str,
    ) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def mqtt_client_ready(self) -> bool: ...
    def mqtt_client_connected(self) -> bool: ...
    def get_state(self) -> GcodeState: ...
    def stop_print(self) -> bool: ...
    def wifi_signal(self) -> str | None: ...
